server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: PRODUCT-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/food_ordering
#    username: root
#    password: 123456